version: "3.3"
services:
  mongodb:
    container_name: mongodb-container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - /home/devuser/mongodb/database:/data/db
    ports:
      - "27017:27017"
    networks:
      - batch
  mongo-express:
    container_name: mongo-express-container
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - batch
networks:
  batch:
    driver: "bridge"