server:
  port: 8085

spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: user
      username: mongo
      password: mongo
  batch:
    job:
      enabled: false